# Generated by Django 3.2.4 on 2021-06-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Article Name', max_length=244)),
                ('content', models.TextField(default='Content')),
                ('count_views', models.IntegerField(default=0)),
            ],
        ),
    ]
